"""Generate a .env.schema from an existing .env.

Infers a type per variable, flags likely secrets, and — critically — never
writes any value into the schema. The schema is a contract, not a secret store.
"""

from __future__ import annotations

import re

from .parser import ParsedEnv
from .secrets import looks_like_secret_key

_URL_RE = re.compile(r"^[a-zA-Z][a-zA-Z0-9+.\-]*://[^\s]+$")
_EMAIL_RE = re.compile(r"^[^@\s]+@[^@\s]+\.[^@\s]+$")
_BOOL_VALUES = {"true", "false", "yes", "no", "on", "off"}


def infer_type(value: str) -> str:
    v = value.strip()
    if v.lower() in _BOOL_VALUES:
        return "bool"
    if _URL_RE.match(v):
        return "url"
    if _EMAIL_RE.match(v):
        return "email"
    if re.fullmatch(r"[+-]?\d+", v):
        return "int"
    if re.fullmatch(r"[+-]?\d*\.\d+", v):
        return "float"
    return "string"


def render_schema_yaml(parsed: ParsedEnv) -> str:
    """Build a clean, deterministic .env.schema YAML (values stripped)."""
    lines = [
        "# Generated by `envcontract init`. Commit this file; it contains no secret values.",
        "version: 1",
        "variables:",
    ]
    seen: set[str] = set()
    for entry in parsed.entries:
        if entry.key in seen:
            continue
        seen.add(entry.key)
        vtype = infer_type(entry.value)
        secret = looks_like_secret_key(entry.key)
        lines.append(f"  {entry.key}:")
        lines.append(f"    type: {vtype}")
        lines.append("    required: true")
        if secret:
            lines.append("    secret: true")
    return "\n".join(lines) + "\n"
